version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          start-command: 'npm run'
          parallelism: 4

       - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file