version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          start-command: 'npm run'
          parallel: true
          parallelism: 4

          artifacts:
      when: always
      paths:
        - cypress/videos/**/*
        - cypress/screenshots/**/*