version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          store_artifacts: true
          parallel: true
          parallelism: 3
          group: 2 machines
